#!/bin/sh
###############################################################################
##                           Copyright (c) 2024                              ##
##                         Rosetta H&S Integrated                            ##
###############################################################################
##  Permission is hereby granted, free of charge, to any person obtaining    ##
##        a copy of this software and associated documentation files         ##
##  (the "Software"), to deal in the Software without restriction, including ##
##     without limitation the right to use, copy, modify, merge, publish,    ##
##     distribute, sublicense, and or sell copies of the Software, and to    ##
##         permit persons to whom the Software is furnished to do so,        ##
##                     subject to the following conditions:                  ##
###############################################################################
## The above copyright notice and this permission notice shall be included   ##
##          in all copies or substantial portions of the Software.           ##
###############################################################################
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS   ##
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF                ##
## MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    ##
## IN NO EVENT SHALL THE   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY    ##
## CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT ##
## OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR  ##
## THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                ##
###############################################################################

#===#===#===#===# Global Constants #===#===#===#===#
readonly EXEC_NAME="${0##*/}"
readonly EXEC_DIR=$(dirname $(realpath $0))

#===#===#===#===# Global Variables #===#===#===#===#
ANSI=true
VERBOSE=false
AUTOYES=false

#===#===#===#===# Info retrieval for Main App #===#===#===#===#
if [ "$1" = "--info" ]; then
    echo "Add Packages from selected Repositories."
    exit
fi
	 

#===#===#===#===# Load Commons #===#===#===#===#
if [ ! "$DATA_DIR" ]; then
    echo " --- [X]: You cannot run Packer utilities manually. Run them properly, with \"packer $EXEC_NAME\""
    exit 100
fi
[ $_PKG_COMMON_LOADED ] || . "$DATA_DIR/Common.sh"

#===#===#===#===# Usage #===#===#===#===#
Usage() {
    echo ""
    echo "$EXEC_NAME v$EXEC_VER - The Link applet for Packer."
    echo "  Copyright 2024 - Rosetta HSI. This software comes with absolutely"
    echo "  NO WARRANTY and is released under the MIT License."
    echo ""
    echo "  This utility is automatically ran after \"packer add\" and \"packer remove\""
    echo "  It is used to make installed packages available to the Orion Operating System."
    echo ""
    echo "  --- Usage: $PACKER_EXEC_NAME $EXEC_NAME [options...]"
    echo "       $ $PACKER_EXEC_NAME $EXEC_NAME -v"
    echo "       $ $PACKER_EXEC_NAME $EXEC_NAME -o /Packages"
    echo ""
    echo "  --- Link Flags:"
    echo "    -o : The path to the Packer environment. By default, this will be \"/Packages\""
    echo ""
    echo "  --- Global Flags:"
    echo "    -h : Display this Help message."
    echo ""
    echo "    -Y : Automatically answers \"y\" to all prompts. DANGEROUS!"
    echo ""
    echo "    -v : Enable verbose logging."
    echo ""
    echo "    -@ : No ANSI escape sequences for color or prompts."
    echo ""
    exit $1
}

#===#===#===#===# Read options from cmdline #===#===#===#===#
Get_Options() {
    while getopts @hvYo: flag
    do
        case "${flag}" in
            @) ANSI=false;;
            h) Build_Usage 0;;
            v) VERBOSE=true;;
            Y) AUTOYES=true;;
            o) PACKERDIR="${OPTARG}";;
            *) Usage $ERR_INVALID_OPTION;;
        esac
    done
}

#===#===#===#===# Entry #===#===#===#===#
Main() {
    Info "$EXEC_NAME $1 $2 $3"
}

Main "$@"; exit $?
