#!/bin/sh
###############################################################################
##                           Copyright (c) 2024                              ##
##                         Rosetta H&S Integrated                            ##
###############################################################################
##  Permission is hereby granted, free of charge, to any person obtaining    ##
##        a copy of this software and associated documentation files         ##
##  (the "Software"), to deal in the Software without restriction, including ##
##     without limitation the right to use, copy, modify, merge, publish,    ##
##     distribute, sublicense, and or sell copies of the Software, and to    ##
##         permit persons to whom the Software is furnished to do so,        ##
##                     subject to the following conditions:                  ##
###############################################################################
## The above copyright notice and this permission notice shall be included   ##
##          in all copies or substantial portions of the Software.           ##
###############################################################################
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS   ##
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF                ##
## MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    ##
## IN NO EVENT SHALL THE   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY    ##
## CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT ##
## OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR  ##
## THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                ##
###############################################################################

#===#===#===#===# Global Constants #===#===#===#===#
readonly EXEC_NAME="${0##*/}"
readonly EXEC_DIR=$(dirname $(realpath $0))
export   DATA_DIR="$EXEC_DIR"
export   APK_VERSION=$("$DATA_DIR/apk.static" --quiet --version)

#===#===#===#===# Global Variables #===#===#===#===#
ANSI=true
VERBOSE=false
AUTOYES=false

#===#===#===#===# Load Commons #===#===#===#===#
[ $_PKG_COMMON_LOADED ] || . "$EXEC_DIR/Common.sh"

#===#===#===#===# Print Applets #===#===#===#===#
Print_Applets() {
    
    APPLETS=$(ls "$DATA_DIR/Applets")
    for APPLET in $APPLETS; do
        APPLET_INFO=$("$DATA_DIR/Applets/$APPLET" --info)
        line='        :'
        printf "    ${TXT_BOLD}%s %s ${TXT_RESET}%s\n" $APPLET "${line:${#APPLET}}" "$APPLET_INFO"
    
    done
}

#===#===#===#===# Usage #===#===#===#===#
Packer_Usage() {
    if [ $ANSI = false ]; then
        local TXT_BOLD=""
        local TXT_RESET=""
        local TXT_UNDERLINE=""
        local OFF_UNDERLINE=""
    fi
    echo -e ""
    echo -e "${TXT_BOLD}${EXEC_NAME} v${EXEC_VER} -${TXT_RESET} The Package Manager for the Orion Operating System."
    echo -e "  Copyright 2024 - Rosetta HSI. This software comes with absolutely"
    echo -e "  NO WARRANTY and is released under the MIT License."
    echo -e ""
    echo -e "  This utility is a front-end for the Alpine Package Keeper"
    echo -e "         (${TXT_UNDERLINE}${APK_VERSION}${OFF_UNDERLINE})"
    echo -e ""
    echo -e "  ${TXT_BOLD}--- Usage: $EXEC_NAME <Applet> [options...]"
    echo -e "       $ $EXEC_NAME add fortune -v"
    echo -e "       $ $EXEC_NAME remove coreutils -Y${TXT_RESET}"
    echo -e ""
    echo -e "  ${TXT_BOLD}--- Applets:${TXT_RESET}"
    Print_Applets
    # echo -e "    add    : Add Packages from selected Repositories."
    # echo -e "    remove : Remove Packages installed on this System."
    # echo -e "    search : Search for Packages with a given search term."
    # echo -e "    fetch  : Download Packages directly from selected Repositories."
    echo -e ""
    echo -e "  ${TXT_BOLD}--- Global Flags:"
    echo -e "    ${TXT_BOLD}-h :${TXT_RESET} Display this Help message."
    echo -e ""
    echo -e "    ${TXT_BOLD}-Y :${TXT_RESET} Automatically answers \"y\" to all prompts. DANGEROUS!"
    echo -e ""
    echo -e "    ${TXT_BOLD}-v :${TXT_RESET} Enable verbose logging."
    echo -e ""
    echo -e "    ${TXT_BOLD}-@ :${TXT_RESET} No ANSI escape sequences for color or prompts. "
    echo -e ""
    exit $1
}

#===#===#===#===# Entry #===#===#===#===#
Main() {
    APPLET="$1"
    #===#===#===> Applet:help
    if [ "$APPLET" = "" ] || [ "$APPLET" = "help" ] || [ "$APPLET" = "-h" ]; then
        Packer_Usage 0
    fi
    
    #===#===#===> Run any Applet
    if [ -e "$DATA_DIR/Applets/$APPLET" ]; then
        shift 1
        export PACKER_EXEC_NAME="$EXEC_NAME"
        exec "$DATA_DIR/Applets/$APPLET" "$@"
    else
    #===#===#===> Applet:???
        Error "Unknown Applet \"$APPLET\"" $ERR_INVALID_OPTION
    fi 
    

}

Main "$@"; exit $?